### ISSUE TITLE
Getting error: No interpreter found for executable name `some-new-mcp` in managed installations or search path

### ISSUE THREAD

**Issue by tech4life87** [modelcontextprotocol/create-python-server#5]
I am trying to create a new MCP server using both pip and uv create-mcp-server command and I am getting the error below.

No interpreter found for executable name `mcp-server` in managed installations or search path

Development setup.
python --version
Python 3.12.5

uv --version
uv 0.5.4 (c62c83c37 2024-11-20)

` ~/model_context_protocol  uvx create-mcp-server
Installed 6 packages in 635ms
Creating a new MCP server project using uv.
This will set up a Python project with MCP dependency.

Let's begin!

Project name (required): mcp-server
Project description [A MCP server project]:
Project version [0.1.0]:
Project will be created at: /s3-mcp-server
Is this correct? [Y/n]: y
error: No interpreter found for executable name `s3-mcp-server` in managed installations or search path
❌ Error: Failed to initialize project.`

**Comment by jspahrsummers** [comment]
Could you please share the paths to your `python` and `uv` installations (`which python` and `which uv`)?

**Comment by tech4life87** [comment]
> Could you please share the paths to your `python` and `uv` installations (`which python` and `which uv`)?

I am using pyenv. But it seems to be an issue with using virtualenv with pyenv
~/.pyenv/shims/python

virtualenv path
/Users/user/.pyenv/versions/3.12.5/envs/some-new-mcp

**Comment by tech4life87** [comment]
As a workaround to this issue. 

1. Install python using uv `uv python install 3.12`
2. Create project `uvx --python 3.12 create-mcp-server`

**Comment by dsp-ant** [comment]
I wonder if you ran into https://github.com/astral-sh/uv/issues/6204 or something similar. It's good to know. We should see if can add this to the troubleshooting section. I'll close this for now since it seems to be a uv + pyvenv interaction, but we keep in mind that there are issues with those.
